### ISSUE TITLE
When trying to use this.

### ISSUE THREAD

**Issue by misilot** [brandonaaron/redmine_rubycas#1]
I am trying to use this plugin but I am getting the error below:

```
(in /srv/redmine-2.2.2)
rake aborted!
Missing :cas_base_url parameter!
/srv/redmine-2.2.2/plugins/redmine_rubycas/lib/redmine_rubycas.rb:27:in `configure!'
/srv/redmine-2.2.2/plugins/redmine_rubycas/init.rb:37:in `<top (required)>'
/srv/redmine-2.2.2/lib/redmine/plugin.rb:130:in `block in load'
/srv/redmine-2.2.2/lib/redmine/plugin.rb:121:in `each'
/srv/redmine-2.2.2/lib/redmine/plugin.rb:121:in `load'
/srv/redmine-2.2.2/config/initializers/30-redmine.rb:12:in `<top (required)>'
/srv/redmine-2.2.2/config/environment.rb:14:in `<top (required)>
```

I am unable to get to the configuration for it in redmine, as it causes redmine passanger to die.

**Comment by brandonaaron** [comment]
Fixed with 9dd1e0324cd6b8638773a38d6ee998c06aaa7534

**Comment by misilot** [comment]
I am now getting the following:

```
rake redmine:plugins:migrate RAILS_ENV=production
(in /srv/redmine-2.2.2)
rake aborted!
cannot load such file -- casclient
/srv/redmine-2.2.2/plugins/redmine_rubycas/lib/redmine_rubycas.rb:2:in `<top (required)>'
/srv/redmine-2.2.2/plugins/redmine_rubycas/init.rb:1:in `<top (required)>'
/srv/redmine-2.2.2/lib/redmine/plugin.rb:130:in `block in load'
/srv/redmine-2.2.2/lib/redmine/plugin.rb:121:in `each'
/srv/redmine-2.2.2/lib/redmine/plugin.rb:121:in `load'
/srv/redmine-2.2.2/config/initializers/30-redmine.rb:12:in `<top (required)>'
/srv/redmine-2.2.2/config/environment.rb:14:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)

```

**Comment by brandonaaron** [comment]
Did you run bundle install?

**Comment by misilot** [comment]
yes

```
Using i18n (0.6.1)
Using multi_json (1.5.0)
Using activesupport (3.2.11)
Using rubycas-client (2.3.9)
Using bundler (1.2.3)
Your bundle is complete! Use `bundle show [gemname]` to see where a bundled
gem is installed.
```

**Comment by brandonaaron** [comment]
And it still says it cannot require casclient?

**Comment by misilot** [comment]
After removing rubycas-client and reinstalling it, it seemed to work.

Thanks!
